version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=calculator
      - DOCKER_INFLUXDB_INIT_BUCKET=calculator_logs
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=eoHE0-Zg85yJEU3EO6EVJ4912W2riiU9mFvU_aFAME5Hfg7SisMeXTnG4HvfH0Tnr4traXNGEy7rwjW4WceWBQ==
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  influxdb_data: 